Refactor tokenizer to use Snowball stemmer for English.
DhiaBou/FullTextSearch pull request #4
Opened 2024-12-10 21:20 UTC by DhiaBou

Replaced the custom token processing logic with the Snowball stemming library for enhanced linguistic precision. Migrated tokenizer code out of the inverted index module and introduced a dedicated Snowball integration for English stemming. Updated build configuration to include necessary object files and reorganized file structure for clarity.

2024-12-13 16:45 UTC, Julian-JP reviewed
Looks good

2024-12-13 19:03 UTC, nicleosch requested changes
Really good idea to use the Snowball library!

Just one issue: The object files contain native machine code, thus the code is not portable any more.
I checked the snowball library myself and you could just include some source code (.c) files to solve this issue. To be precise, including the following files in the build should make it work:
- runtime/api.c
- runtime/utilities.c
- src_c/stem_UTF_8_english.c

2024-12-15 20:27 UTC, nicleosch commented
Looks good now. 👍 
Since you also changed the CLI, maybe remove the extra empty line after each query output, there is no need for this anymore imo.

2024-12-16 11:53 UTC, nicleosch approved these changes

2024-12-16 13:24 UTC, merged